// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// cxxMixSquarem
List cxxMixSquarem(NumericMatrix matrix_lik, NumericVector prior, NumericVector pi_init, List control);
RcppExport SEXP ashr_cxxMixSquarem(SEXP matrix_likSEXP, SEXP priorSEXP, SEXP pi_initSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< NumericMatrix >::type matrix_lik(matrix_likSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type prior(priorSEXP );
        Rcpp::traits::input_parameter< NumericVector >::type pi_init(pi_initSEXP );
        Rcpp::traits::input_parameter< List >::type control(controlSEXP );
        List __result = cxxMixSquarem(matrix_lik, prior, pi_init, control);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
