# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cxxMixSquarem <- function(matrix_lik, prior, pi_init, control) {
    .Call('ashr_cxxMixSquarem', PACKAGE = 'ashr', matrix_lik, prior, pi_init, control)
}

