# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cxxMixEM <- function(matrix_lik, prior, pi_init, tol = 0.0001, maxiter = 5000L) {
    .Call('ashr_cxxMixEM', PACKAGE = 'ashr', matrix_lik, prior, pi_init, tol, maxiter)
}
