# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Brief description of function.
#' @description Explain here what this function does.
#' @param matrix_lik Description of argument goes here.
#' @param prior Description of argument goes here.
#' @param pi_init Description of argument goes shere.
#' @param control Description of argument goes here.
#' @export
cxxMixSquarem <- function(matrix_lik, prior, pi_init, control) {
    .Call('_ashr_cxxMixSquarem', PACKAGE = 'ashr', matrix_lik, prior, pi_init, control)
}

